fix: Initial support for iFrame launcher
valorkin/ng-mf-submodules pull request #40
Opened 2020-10-03 11:19 UTC by fkolar

This demostrate basic iFrame usage, comunication betwen frames. 
Please read the `IFrameLauncherComponent.ts` for more information. What is left to be implemented.

2020-10-05 11:01 UTC, valorkin requested changes
not having an iFrame page doesn't allows to should bundle and performance advantages of MF approach over iFrames
which would a great thing for Manav slides

2020-10-05 11:01 UTC, valorkin commented on packages/iframe-source-website/src/app/app.component.html
> +    <fd-icon [size]="'s'" glyph="activity-items" ></fd-icon>
Please, don't use bindings where they not needed

2020-10-05 11:01 UTC, valorkin commented on packages/iframe-source-website/src/app/app.component.ts
> +      window.addEventListener('message', this.onMessage, false);
Your code will be copy pasted 10 to 1, add remove listener in on destroy, please

2020-10-05 11:01 UTC, valorkin commented on packages/iframe-source-website/src/index.html
> +  <link href="https://sap.github.io/fundamental-ngx/styles.1aa62a8b4b599ef5e758.css" rel="stylesheet">
Better to use unpkg.com links to css, they are versioned and immutable

2020-10-05 11:01 UTC, valorkin commented on packages/one-bx-shell-app/src/app/components/iframe-launcher/iframe-launcher.component.ts
> +  id: string;
We shouldn't have an id here, same as feature launcher

2020-10-05 11:01 UTC, valorkin commented on mf-builder/package.json
> +    "ts-loader": "^6.2.2",
package-lock remove, but yarn lock is not updated. We have to use `yarn install` anyway, so not critical but would be nice

2020-10-05 11:01 UTC, valorkin commented on packages/iframe-source-website/src/styles.scss
> +  position: relative;
taking in account folks like fieldglass, who are no planning to changing anything for us, we could try inject this styles via contentWindow

2020-10-05 11:01 UTC, valorkin commented on packages/one-bx-shell-app/src/app/components/iframe-launcher/iframe-launcher.component.scss
> +  with: 100%;
width

2020-10-05 11:01 UTC, valorkin commented on packages/one-bx-shell-app/src/app/components/iframe-launcher/iframe-launcher.component.html
> +<div class="responsive-wrapper"
is there any particular reason for wrapper? is there are some specific browser issues?
if there are no specific browser issues, we don't need any wrapper
styles could be applied directly to iframe

2020-10-05 11:01 UTC, valorkin commented on packages/one-bx-shell-app/src/app/components/iframe-launcher/iframe-launcher.component.html
> +          frameborder="no">
`frameborder` it appear to be deprecated, css `border` should be used instead
`scrolling` is deprecated too BTW

2020-10-05 11:01 UTC, valorkin commented on packages/one-bx-shell-app/src/app/components/iframe-launcher/iframe-launcher.component.ts
> +  @Input()
`title` seems to be unused

2020-10-05 11:01 UTC, valorkin commented on packages/one-bx-shell-app/src/app/components/iframe-launcher/iframe-launcher.component.ts
> +  id: string;
for managed resource, I believe we should couple of agreements:
- one config per resource (host)
- we should not `process` id's, like split by dot (`fieldglass.login`)
- we should have 2 properties to identify what we want to inject from config: app name and component name

@fkolar thoughts?

and yes It's important now :)

2020-10-05 11:01 UTC, valorkin commented on packages/one-bx-shell-app/src/app/components/iframe-launcher/iframe-launcher.component.ts
> +    if (changes.url) {
and support for managed components please https://github.com/valorkin/ng-mf-submodules/pull/37/files#diff-9477e05dc3cebab0d7790cdb6996216e

we should have plugin\iframe\webcomponents launcher on pair from day zero

with fallback to url if you want, but managed resources should be a priority
switching from urls to configs will be a breaking change for our consumers
plus with configs, we will be able to do a build\CI checks for proper URIs
with URLs for iFrames we will not

2020-10-05 11:01 UTC, valorkin commented on packages/one-bx-shell-app/src/app/components/iframe-launcher/iframe-launcher.component.ts
> +    setTimeout(() => {
1. as far as I understood this component will be moved to app-shell? if so, this should not be here
2. but this is good use case, because we may need to bubble a `load` event from iFrame

2020-10-05 11:01 UTC, valorkin commented on packages/one-bx-shell-app/src/app/components/iframe-launcher/iframe-launcher.component.ts
> +      window.addEventListener('message', this.onMessage, false);
this should not be done here, it should be done once per shell lifetime, in a service responsible for communication

2020-10-05 11:01 UTC, valorkin commented on packages/one-bx-shell-app/src/app/components/iframe-launcher/iframe-launcher.component.ts
> +  private onMessage(e: any): void {
no need to be here

2020-10-05 11:01 UTC, valorkin commented on packages/one-bx-shell-app/src/app/components/iframe-launcher/iframe-launcher.component.ts
> +      this.iframeHandle = this.iframeEl.nativeElement.contentWindow;
it's a memory leak, if not cleaned onDestroy and `url` change

2020-10-05 11:01 UTC, valorkin commented on packages/one-bx-shell-app/src/app/components/plugin-launcher/plugin-launcher.component.ts
> +export class PluginLauncherComponent implements OnChanges {
copy from appshell? why

2020-10-05 11:01 UTC, valorkin commented on packages/webcomp-auth-app/component.ts
> +import * as rxjs from 'rxjs';
I don't see any usages of rxjs?

2020-10-05 11:07 UTC, fkolar commented
@valorkin please, update it as you need to I will not touch this PR, I tried to move this forward as on last week we were behind so this should get you started. 

also please see my comments. inlined

2020-10-05 11:08 UTC, fkolar commented on mf-builder/package.json
> +    "ts-loader": "^6.2.2",
already removed thsi in my last commit

2020-10-05 11:08 UTC, fkolar commented on packages/one-bx-shell-app/src/app/components/iframe-launcher/iframe-launcher.component.ts
> +      window.addEventListener('message', this.onMessage, false);
here I expect you replace with your communication api you have been working on last week. this is not final code this is just setup which way we shouldbe going

2020-10-05 11:09 UTC, fkolar commented on packages/one-bx-shell-app/src/app/components/iframe-launcher/iframe-launcher.component.ts
> +      this.iframeHandle = this.iframeEl.nativeElement.contentWindow;
please see my comment above.

2020-10-05 11:10 UTC, fkolar commented on packages/one-bx-shell-app/src/app/components/plugin-launcher/plugin-launcher.component.ts
> +export class PluginLauncherComponent implements OnChanges {
it easier to debug and extend while working on Webcomponent. I expect that you will add down the road some code for iFrame, once we  have both in webcomponents and iFrame we can update app-shell

2020-10-05 11:11 UTC, fkolar commented on packages/webcomp-auth-app/component.ts
> +import * as rxjs from 'rxjs';
This is example from Manfred, and throwaway code, once you finalize this iFrame support.

2020-10-05 12:22 UTC, valorkin commented on packages/iframe-source-website/src/index.html
> +  <link href="https://sap.github.io/fundamental-ngx/styles.1aa62a8b4b599ef5e758.css" rel="stylesheet">
ok, they doesn't have bundle in npm package, add imports to `styles` file then

2020-10-08 09:36 UTC, valorkin commented
merged in #37

2020-10-08 09:36 UTC, closed without merging