feat: added ability to mf-builder to built and expose nx-app
valorkin/ng-mf-submodules pull request #5
Opened 2020-09-22 15:37 UTC by ZhmenZH

2020-09-23 06:37 UTC, fkolar requested changes
Can create a component under apps also which uses shared component from libs/ and expose that one ? You can move of the othe component from `libs` to apps

2020-09-23 11:03 UTC, fkolar approved these changes

2020-09-25 11:02 UTC, valorkin requested changes
rollback foreign package.json and package-lock`s

2020-09-25 12:43 UTC, valorkin approved these changes

2020-09-25 12:43 UTC, merged