Angular Web Component
valorkin/ng-mf-submodules pull request #59
Opened 2020-10-19 12:27 UTC by ZhmenZH

2020-10-19 12:30 UTC, fkolar approved these changes, later dismissed

2020-10-19 12:31 UTC, fkolar commented
@valorkin can we merge, not sure if you have something in progress ..

2020-10-19 13:31 UTC, valorkin commented
@fkolar I am working on builder, I will rebase later on

2020-10-20 08:27 UTC, valorkin requested changes
couple of minor changes please
except this looks good to me

2020-10-20 08:27 UTC, valorkin commented on packages/cflp-app/lib/cart.consumer.ts
> +const GetDefaultCartAction = 'defaultCartState';
change `default` to `current` and in Theme too, sorry, I forgot to change it

2020-10-20 08:27 UTC, valorkin commented on packages/content-item-app/lib/cart.provider.ts
> +const GetDefaultCartAction = 'defaultCartState';
here too `default` -> `current` please

2020-10-20 08:27 UTC, valorkin commented on packages/content-item-app/src/app/item-page/item-page.component.ts
> +    console.log('onAddToCart event', );
please remove if not intended

2020-10-20 09:40 UTC, valorkin approved these changes
looks good enough to me
@fkolar ready to merge

2020-10-20 09:42 UTC, fkolar approved these changes

2020-10-20 09:42 UTC, merged